### ISSUE TITLE
emr-tls-security fails on EMR 5.22 or later

### ISSUE THREAD

**Issue by secpaul** [aws-samples/emr-tls-security#1]
An EMR cluster deployed with the provided .jar fails to deploy on EMR 5.22 or later. The error provided is "Master instance startup failed due to an internal error". 

I believe the issue is related to the use of AWS Java SDK from version 1.10.x as a dependency  (specifically the Lambda dependency). Updating these to 1.11.170 appears to work but I do not know what issue this causes for backward compatibility (I have tested 5.11 and it works).

**Comment by RemekHet** [comment]
New build supporting EMR 5.22 was added. Source code, jar as well as CFN template located in emr-5.22+ folder
