### ISSUE TITLE
emr-tls-ssm-0.2.jar does not work

### ISSUE THREAD

**Issue by JituS** [aws-samples/emr-tls-security#2]
I followed [this](https://aws.amazon.com/blogs/big-data/encrypt-data-in-transit-using-a-tls-custom-certificate-provider-with-amazon-emr/) blog, with the latest version on emr, I am facing issue.
Error is `Terminated with errorsOn the master instance (i-041b4c6a66c19e01d), Certificate installation failed due to internal error.` 
This occurring on emr > 5.21.1 with emr-tls-ssm-0.2.jar . I was able to install certificates with emr-5.21.1 using emr-tls-ssm-0.2.jar.
I looked into the emr logs, but no luck.

**Comment by JituS** [comment]
I think I found the problem. The issue is, in emr-tls-ssm-0.2, we have stopped using lambda function to get SSM parameter and directly querying for that from java code using `GetParameterRequest` class. for that to work, instance role must have ssn:GetParameter permission. This information can be added to the blog.

**Comment by RemekHet** [comment]
CloudFormation template in folder 5.22+ that creates IAM EC2 Role from EMR, has included permission for SSM
